version: "3"
services: 
  jenkins:
    image: jenkins/jenkins
    user: root
    container_name: jenkins
    ports: 
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./www:/var/www/
      - /var/run/docker.sock:/var/run/docker.sock